services:

  db:
    image: postgres
    container_name: whatsapp-web-postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    network_mode: "host"

  web-server:
    build: .
    container_name: whatsapp-web-server
    command: bash -c "alembic upgrade head && python main.py"
    env_file:
      - .env
    environment:
      - WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN}
      - GRAPH_API_TOKEN=${GRAPH_API_TOKEN}
    restart: always
    depends_on:
      - db
    network_mode: "host"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: whatsapp-web-ngrok
    command: http --domain=${DOMAIN} ${PORT}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN}
      - GRAPH_API_TOKEN=${GRAPH_API_TOKEN}
    network_mode: "host"
